export const routes = {
    login: () => '/auth/login',
    signup: () => '/auth/signup',
    forgotPassword: () => '/auth/forgot-password',
    app: () => '/app',
    inbox: () => '/app/inbox',
    myIssues: () => '/app/my-issues',
    projects: () => '/app/projects',
    issues: () => '/app/issues',
    wiki: () => '/app/wiki',
    settings: () => '/settings',
    preferences: () => '/settings/preferences',
    profile: () => '/settings/profile',
    security: () => '/settings/security',
} as const;
