name: PR Checks

on:
    pull_request:
        branches:
            - dev
            - main

jobs:
    webclient:
        name: WebClient - lint, build, test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm run web:ci

            - name: Lint
              run: npm run web:lint

            - name: Build
              run: npm run web:build

            # - name: Test
            #   run: npm test -- --runInBand

    webapi:
        name: WebApi - lint, build, test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm run api:ci

            - name: Lint
              run: npm run api:lint

            - name: Build
              run: npm run api:build

            # - name: Test
            #   run: npm run api:test -- --runInBand
